create table tb_course (workload integer, id bigint generated by default as identity, name varchar(255), primary key (id));
create table tb_student (registration_number integer, course_id bigint, id bigint generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_student add constraint FKhampbkjvm4j2eicf3scylbxmu foreign key (course_id) references tb_course;
INSERT INTO tb_course (name, workload) VALUES ('Análise e Desenvolvimento de Sistemas', 1800); -- ID 1;
INSERT INTO tb_course (name, workload) VALUES ('Engenharia de Software', 2400); -- ID 2;
INSERT INTO tb_course (name, workload) VALUES ('Ciência de Dados', 1500);      -- ID 3;
INSERT INTO tb_student (registration_number, name, course_id) VALUES (1001, 'Caio', 1);
INSERT INTO tb_student (registration_number, name, course_id) VALUES (1002, 'Maria Eduarda', 1);
INSERT INTO tb_student (registration_number, name, course_id) VALUES (2001, 'João Victor', 2);
